name: dotnet ci
on:
  push:
    branches:
      - main

jobs:

  # run build
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: get sources
        uses: actions/checkout@master
        
      - uses: actions/upload-artifact@v2
        with:
          name: sources
          path: source

      - name: install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: build
        run: dotnet build source
  
  # run tests
  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/download-artifact@v2
        with:
          name: sources
      - run: dotnet build
      - name: run tests for Api
        run: dotnet test "ConfigurationManagementSystem.Api.Tests/ConfigurationManagementSystem.Api.Tests.csproj" --no-build --no-restore 
        
      - name: run tests for Domain
        run: dotnet test "ConfigurationManagementSystem.Domain.Tests/ConfigurationManagementSystem.Domain.Tests.csproj" --no-build --no-restore  
        
      - name: run tests for Persistence
        run: dotnet test "ConfigurationManagementSystem.Persistence.Tests/ConfigurationManagementSystem.Persistence.Tests.csproj" --no-build --no-restore

  publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: sources
          
      - name: publish
        run: dotnet publish "ConfigurationManagementSystem.Api/ConfigurationManagementSystem.Api.csproj" -c Release -p:UseAppHost=false -o artifact     
      
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: artifact
          
  release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
      - uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "."
          target: "/var/www/api"
          rm: true
