name: dotnet ci
on:
  push:
    branches:
      - main

jobs:

  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: get sources
        uses: actions/checkout@master

      - name: install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: build
        run: dotnet build source


      #- name: run tests for ConfigurationService.Api
      #  run: dotnet test "source/ConfigurationService.Api.Tests/ConfigurationService.Api.Tests.csproj" --no-build --no-restore 
        
      #- name: run tests for ConfigurationService.Domain
      #  run: dotnet test "source/ConfigurationService.Domain.Tests/ConfigurationService.Domain.Tests.csproj" --no-build --no-restore  
        
      #- name: run tests for ConfigurationService.Persistence
      #  run: dotnet test "source/ConfigurationService.Persistence.Tests/ConfigurationService.Persistence.Tests.csproj" --no-build --no-restore


      - name: publish
        run: dotnet publish -c Release -p:UseAppHost=false

      - name: deploy artifact
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "publish/"
          target: "/var/www/api"
          rm: true
