name: dotnet ci
on:
  push:
    branches:
      - main

jobs:

  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: get sources
        uses: actions/checkout@master

      - name: install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: build
        run: dotnet build

      - name: run tests
        run: dotnet test --no-build --no-restore

      - name: publish
        run: dotnet publish --no-build --no-restore

      - name: deploy artifact
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "publish/"
          target: "/var/www/api"
          rm: true